name: Documentation

on:
  push:
    branches:
      - 'main'
    tags: '*'
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHON: ""
    steps:
      - uses: actions/checkout@v4
      - name: Setup julia
        uses: julia-actions/setup-julia@v2
        with:
            version: '1.11'
      - name: Cache artifacts
        uses: julia-actions/cache@v2
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs/ docs/make.jl