name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ["1.10", "1.11"]
        julia-arch: [x64, x86]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        exclude:
            - os: macOS-latest
              julia-arch: x86

    steps:
    - uses: actions/checkout@v4
    - name: Setup julia
        uses: julia-actions/setup-julia@v2
        with:
            version: ${{ matrix.julia-version }}
            arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
